package com.bridgelab;

/****************************************************************************************
 * @author mihir
 * 
 *This problem simulates a Snake and Ladder Game. 
 *The Player starts from 0 rolls the die to get a number between 1 to 6, 
 *finds a safe place, ladder or a snake keeps doing till the winning spot 100 is achieved.
 ****************************************************************************************/

public class SnakeAndLadder
{	
	final static int noPlayOption = 0;
	final static int snakeOption = 1;
	final static int ladderOption = 2;
	
	static int startPosition = 0;
	static int rollDice;
	static int randomOption;
	
	public static void main(String[] args)
	{	
		while(startPosition < 100)
		{
			//using Math.random() function generating random numbers from range 0 to 2
			randomOption = (int) Math.floor(Math.random()*10) % 3;
			
			//using Math.random() function generating random numbers from range 1 to 6.
			rollDice =(int) (Math.random()*(6))+1;
			System.out.println("Random number generated by dice is : " + rollDice);
			System.out.println("Starting position of the player is : " + startPosition);
			
			if(randomOption == noPlayOption)
			{
				System.out.println("You got No-Play Option!");
			}
			else if(randomOption == snakeOption)
			{
				System.out.println("You got Snake!");
				
				//as player got snake players current position will get reduced by the number generated by dice.
				startPosition -= rollDice;
				
				//checking if players position going below 0 after subtracting dice number if yes then resetting position to again 0. 
				if (startPosition <=0)
				{
					startPosition = 0;
				}
			}
			else
			{
				System.out.println("You got Ladder!");
				
				//incrementing players current position by the random number generated by the dice.
				startPosition += rollDice;
				//if player position crossing 100 then he should brought back to previous position.
				if(startPosition > 100)
				{
					startPosition -= rollDice;
				}
			}
			System.out.println("Curruent position of player is :" + " " + startPosition);
		}
	}
}
