package com.bridgelab;

/****************************************************************************************
 * @author mihir
 * 
 *This problem simulates a Snake and Ladder Game. 
 *The Player starts from 0 rolls the die to get a number between 1 to 6, 
 *finds a safe place, ladder or a snake keeps doing till the winning spot 100 is achieved.
 ****************************************************************************************/

public class SnakeAndLadder
{	
	static int startPosition = 0;
	static int rollDice;
	
	public static void main(String[] args)
	{
		//using Math.random() function generating random numbers from range 1 to 6.
		rollDice =(int) (Math.random()*(6))+1;
		System.out.println("Random number generated by dice is : " + rollDice);
	}
}
